### PR TITLE
Minutes and documents from the Dec/Jan SC meetings

### PR DESCRIPTION
**Pull request by bettinaheim**

### CODE REVIEW

**Review by rtvuser1 — CHANGES_REQUESTED** [review]
Line 49 of Jan 2022 notes should say complementary, note complimentary
On line 52, you might say "evolving a technical solution" to distinguish from the previous line more clearly.
All else seems good and properly reflects what was discussed in the meetings.

**Comment by bettinaheim** [comment]
> Line 49 of Jan 2022 notes should say complementary, note complimentary On line 52, you might say "evolving a technical solution" to distinguish from the previous line more clearly. All else seems good and properly reflects what was discussed in the meetings.

@rtvuser1 Thanks for the review! I fixed the complimentary to say complementary, but I could use some clarification on line 52. Line 52 currently says "is defining and evolving a technical solution. The QIR Alliance can benefit". Do you suggest to remove the part about evolving and have it say "is defining a technical solution. The QIR Alliance can benefit", or do you suggest to say "is evolving a technical solution. The QIR Alliance can benefit"? Or something else?

**Comment by rtvuser1** [comment]
Oh, sorry ... I meant to say "evolving a **_specific_** technical solution" (I left out the specific in my first comment).  That would make it clearer that PIRQ is look at many tech solutions and QIR-Alliance is focusing on a specific one.  That was the idea ...

**Comment by bettinaheim** [comment]
> Oh, sorry ... I meant to say "evolving a **_specific_** technical solution" (I left out the specific in my first comment). That would make it clearer that PIRQ is looking at many tech solutions and QIR-Alliance is focusing on a specific one. That was the idea ...

@rtvuser1 That clarifies it, thanks. I added the word "specific".

**Review by rtvuser1 — APPROVED** [review]

**Pull request merged**
